foreach(ROMODULAR_REQUIRED_VARIABLE
    ROMODULAR_ROOT
    ROMODULAR_PROFILE
    ROMODULAR_EXPECTED_PROCESSOR
    ROMODULAR_EXPECTED_C_FLAGS
    ROMODULAR_EXPECTED_CXX_FLAGS
    ROMODULAR_EXPECTED_LINKER_FLAGS
)
    if(NOT DEFINED ${ROMODULAR_REQUIRED_VARIABLE})
        message(FATAL_ERROR
            "${ROMODULAR_REQUIRED_VARIABLE} is required for toolchain validation"
        )
    endif()
endforeach()

set(ROMODULAR_PROFILE_PATH "${ROMODULAR_ROOT}/${ROMODULAR_PROFILE}")
if(NOT EXISTS "${ROMODULAR_PROFILE_PATH}")
    message(FATAL_ERROR "Toolchain profile does not exist: ${ROMODULAR_PROFILE}")
endif()

# Prevent standalone semantic tests from depending on cross compilers being
# installed. find_program() preserves these already resolved command paths.
set(CMAKE_C_COMPILER "${CMAKE_COMMAND}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${CMAKE_COMMAND}" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${CMAKE_COMMAND}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${CMAKE_COMMAND}" CACHE FILEPATH "" FORCE)

include("${ROMODULAR_PROFILE_PATH}")

set(ROMODULAR_ACTUAL_VALUES
    CMAKE_SYSTEM_PROCESSOR
    CMAKE_C_FLAGS_INIT
    CMAKE_CXX_FLAGS_INIT
    CMAKE_EXE_LINKER_FLAGS_INIT
)
set(ROMODULAR_EXPECTED_VALUES
    ROMODULAR_EXPECTED_PROCESSOR
    ROMODULAR_EXPECTED_C_FLAGS
    ROMODULAR_EXPECTED_CXX_FLAGS
    ROMODULAR_EXPECTED_LINKER_FLAGS
)

list(LENGTH ROMODULAR_ACTUAL_VALUES ROMODULAR_VALUE_COUNT)
math(EXPR ROMODULAR_LAST_VALUE "${ROMODULAR_VALUE_COUNT} - 1")
foreach(ROMODULAR_VALUE_INDEX RANGE ${ROMODULAR_LAST_VALUE})
    list(GET ROMODULAR_ACTUAL_VALUES
        ${ROMODULAR_VALUE_INDEX}
        ROMODULAR_ACTUAL_VARIABLE
    )
    list(GET ROMODULAR_EXPECTED_VALUES
        ${ROMODULAR_VALUE_INDEX}
        ROMODULAR_EXPECTED_VARIABLE
    )
    if(NOT "${${ROMODULAR_ACTUAL_VARIABLE}}" STREQUAL
       "${${ROMODULAR_EXPECTED_VARIABLE}}")
        message(FATAL_ERROR
            "${ROMODULAR_PROFILE}: ${ROMODULAR_ACTUAL_VARIABLE} expected "
            "'${${ROMODULAR_EXPECTED_VARIABLE}}', got "
            "'${${ROMODULAR_ACTUAL_VARIABLE}}'"
        )
    endif()
endforeach()

message(STATUS "Validated toolchain profile ${ROMODULAR_PROFILE}")
