file(STRINGS
    "${CMAKE_CURRENT_LIST_DIR}/../VERSION"
    ROMODULAR_BUILD_VERSION
    LIMIT_COUNT 1
)
string(STRIP "${ROMODULAR_BUILD_VERSION}" ROMODULAR_BUILD_VERSION)

if(NOT ROMODULAR_BUILD_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR
        "Invalid RoModularBuild VERSION: '${ROMODULAR_BUILD_VERSION}'"
    )
endif()
